import type { Asset, DashboardSummary, Endpoint, Finding, Notification, Scan, Target, User, Workspace } from "@/types/pan";

export const mockUser: User = {
  id: "user_analyst_01",
  name: "Maya Chen",
  email: "analyst@pan.local",
  role: "analyst",
  organization: "Northstar Security",
};

export const mockWorkspaces: Workspace[] = [
  { id: "workspace_01", name: "Northstar Cloud", plan: "Hackathon Pro", targetCount: 2, memberCount: 5 },
  { id: "workspace_02", name: "Mobile Research", plan: "Sandbox", targetCount: 1, memberCount: 2 },
];

export const mockTargets: Target[] = [
  {
    id: "target_01",
    name: "Northstar Customer Portal",
    baseUrl: "https://portal.northstar-demo.com",
    domain: "northstar-demo.com",
    environment: "production",
    verificationStatus: "verified",
    verificationMethod: "dns_txt",
    lastScan: "2026-08-27T08:42:00Z",
    assets: 18,
    endpoints: 342,
    findings: 9,
    risk: "high",
    scope: {
      includedHosts: ["portal.northstar-demo.com", "api.northstar-demo.com"],
      excludedHosts: ["payments.northstar-demo.com"],
      includedPaths: ["/*"],
      excludedPaths: ["/logout", "/account/delete", "/billing/charge"],
      allowedPorts: [80, 443],
    },
    authenticationProfile: "Customer test account",
    createdAt: "2026-08-12T10:18:00Z",
  },
  {
    id: "target_02",
    name: "Atlas Partner API",
    baseUrl: "https://sandbox-api.atlas-demo.dev",
    domain: "atlas-demo.dev",
    environment: "staging",
    verificationStatus: "verified",
    verificationMethod: "http_header",
    lastScan: "2026-08-26T16:10:00Z",
    assets: 7,
    endpoints: 128,
    findings: 4,
    risk: "medium",
    scope: {
      includedHosts: ["sandbox-api.atlas-demo.dev"],
      excludedHosts: [],
      includedPaths: ["/v1/*", "/v2/*"],
      excludedPaths: ["/v1/webhooks/test-payment"],
      allowedPorts: [443],
    },
    authenticationProfile: "Partner API token (vaulted)",
    createdAt: "2026-08-18T14:05:00Z",
  },
  {
    id: "target_03",
    name: "Aurora Fintech Web",
    baseUrl: "https://app.aurora-finance.com",
    domain: "aurora-finance.com",
    environment: "production",
    verificationStatus: "verified",
    verificationMethod: "meta_tag",
    lastScan: "2026-08-29T11:20:00Z",
    assets: 26,
    endpoints: 511,
    findings: 14,
    risk: "critical",
    scope: {
      includedHosts: ["app.aurora-finance.com", "api.aurora-finance.com", "cdn.aurora-finance.com"],
      excludedHosts: ["banking.aurora-finance.com"],
      includedPaths: ["/*"],
      excludedPaths: ["/transactions/export", "/admin/delete", "/webhook"],
      allowedPorts: [80, 443, 8443],
    },
    authenticationProfile: "Analyst finance test account",
    createdAt: "2026-08-05T09:00:00Z",
  },
  {
    id: "target_04",
    name: "Pulse Mobile API",
    baseUrl: "https://api.pulse-mobile.io",
    domain: "pulse-mobile.io",
    environment: "development",
    verificationStatus: "pending",
    verificationMethod: "file",
    lastScan: null,
    assets: 5,
    endpoints: 64,
    findings: 2,
    risk: "low",
    scope: {
      includedHosts: ["api.pulse-mobile.io"],
      excludedHosts: [],
      includedPaths: ["/v3/*"],
      excludedPaths: ["/v3/admin"],
      allowedPorts: [443],
    },
    authenticationProfile: null,
    createdAt: "2026-08-22T15:30:00Z",
  },
  {
    id: "target_05",
    name: "Nexus Healthcare",
    baseUrl: "https://portal.nexushealth.org",
    domain: "nexushealth.org",
    environment: "staging",
    verificationStatus: "verified",
    verificationMethod: "html_file",
    lastScan: "2026-08-28T18:05:00Z",
    assets: 33,
    endpoints: 478,
    findings: 12,
    risk: "high",
    scope: {
      includedHosts: ["portal.nexushealth.org", "api.nexushealth.org"],
      excludedHosts: ["intake.nexushealth.org"],
      includedPaths: ["/*"],
      excludedPaths: ["/phr/download", "/auth/force-reset"],
      allowedPorts: [443],
    },
    authenticationProfile: "Analyst clinician account",
    createdAt: "2026-08-10T12:45:00Z",
  },
];

export const mockAssets: Asset[] = [
  { id: "asset_01", targetId: "target_01", targetName: "Northstar Customer Portal", hostname: "portal.northstar-demo.com", domain: "northstar-demo.com", ip: "203.0.113.42", port: 443, protocol: "https", httpStatus: 200, pageTitle: "Northstar Portal", technologies: ["Next.js", "Cloudflare", "React"], tls: "TLS 1.3 · valid 61d", firstSeen: "2026-08-12T10:30:00Z", lastSeen: "2026-08-27T08:51:00Z", discoverySource: "HTTPx", risk: "high", type: "live_host" },
  { id: "asset_02", targetId: "target_01", targetName: "Northstar Customer Portal", hostname: "api.northstar-demo.com", domain: "northstar-demo.com", ip: "203.0.113.44", port: 443, protocol: "https", httpStatus: 200, pageTitle: "Northstar API", technologies: ["FastAPI", "Python", "nginx"], tls: "TLS 1.3 · valid 61d", firstSeen: "2026-08-12T10:32:00Z", lastSeen: "2026-08-27T08:50:00Z", discoverySource: "Subfinder", risk: "medium", type: "subdomain" },
  { id: "asset_03", targetId: "target_01", targetName: "Northstar Customer Portal", hostname: "cdn.northstar-demo.com", domain: "northstar-demo.com", ip: "198.51.100.21", port: 443, protocol: "https", httpStatus: 200, pageTitle: "Static content", technologies: ["CloudFront", "Amazon S3"], tls: "TLS 1.3 · valid 44d", firstSeen: "2026-08-14T09:20:00Z", lastSeen: "2026-08-27T08:49:00Z", discoverySource: "DNS", risk: "low", type: "subdomain" },
  { id: "asset_04", targetId: "target_01", targetName: "Northstar Customer Portal", hostname: "status.northstar-demo.com", domain: "northstar-demo.com", ip: "192.0.2.17", port: 443, protocol: "https", httpStatus: 200, pageTitle: "Northstar Status", technologies: ["Statuspage"], tls: "TLS 1.2 · valid 89d", firstSeen: "2026-08-20T11:00:00Z", lastSeen: "2026-08-27T08:47:00Z", discoverySource: "Certificate transparency", risk: "none", type: "subdomain" },
  { id: "asset_05", targetId: "target_02", targetName: "Atlas Partner API", hostname: "sandbox-api.atlas-demo.dev", domain: "atlas-demo.dev", ip: "198.51.100.88", port: 443, protocol: "https", httpStatus: 200, pageTitle: "Atlas API", technologies: ["Go", "Kubernetes", "Envoy"], tls: "TLS 1.3 · valid 72d", firstSeen: "2026-08-18T14:12:00Z", lastSeen: "2026-08-26T16:20:00Z", discoverySource: "HTTPx", risk: "medium", type: "live_host" },
  { id: "asset_06", targetId: "target_02", targetName: "Atlas Partner API", hostname: "docs.atlas-demo.dev", domain: "atlas-demo.dev", ip: "198.51.100.90", port: 443, protocol: "https", httpStatus: 200, pageTitle: "Atlas API Documentation", technologies: ["Redoc", "OpenAPI"], tls: "TLS 1.3 · valid 72d", firstSeen: "2026-08-18T14:14:00Z", lastSeen: "2026-08-26T16:18:00Z", discoverySource: "Katana", risk: "low", type: "subdomain" },
  { id: "asset_07", targetId: "target_03", targetName: "Aurora Fintech Web", hostname: "app.aurora-finance.com", domain: "aurora-finance.com", ip: "203.0.113.120", port: 443, protocol: "https", httpStatus: 200, pageTitle: "Aurora Banking", technologies: ["React", "Cloudflare", "nginx"], tls: "TLS 1.3 · valid 92d", firstSeen: "2026-08-05T09:10:00Z", lastSeen: "2026-08-29T11:22:00Z", discoverySource: "HTTPx", risk: "critical", type: "live_host" },
  { id: "asset_08", targetId: "target_03", targetName: "Aurora Fintech Web", hostname: "api.aurora-finance.com", domain: "aurora-finance.com", ip: "203.0.113.122", port: 443, protocol: "https", httpStatus: 200, pageTitle: "Aurora API", technologies: ["Go", "Kong", "Kubernetes"], tls: "TLS 1.3 · valid 92d", firstSeen: "2026-08-05T09:14:00Z", lastSeen: "2026-08-29T11:20:00Z", discoverySource: "Subfinder", risk: "high", type: "live_host" },
  { id: "asset_09", targetId: "target_03", targetName: "Aurora Fintech Web", hostname: "payments.aurora-finance.com", domain: "aurora-finance.com", ip: "203.0.113.125", port: 443, protocol: "https", httpStatus: 403, pageTitle: "Aurora Payments", technologies: ["nginx", "Node.js"], tls: "TLS 1.3 · valid 90d", firstSeen: "2026-08-06T10:00:00Z", lastSeen: "2026-08-29T11:18:00Z", discoverySource: "Certificate transparency", risk: "medium", type: "subdomain" },
  { id: "asset_10", targetId: "target_03", targetName: "Aurora Fintech Web", hostname: "mobile.aurora-finance.com", domain: "aurora-finance.com", ip: "203.0.113.130", port: 443, protocol: "https", httpStatus: 200, pageTitle: "Aurora Mobile", technologies: ["Flutter", "Cloudflare"], tls: "TLS 1.3 · valid 91d", firstSeen: "2026-08-09T12:00:00Z", lastSeen: "2026-08-29T11:16:00Z", discoverySource: "Katana", risk: "low", type: "subdomain" },
  { id: "asset_11", targetId: "target_05", targetName: "Nexus Healthcare", hostname: "portal.nexushealth.org", domain: "nexushealth.org", ip: "192.0.2.200", port: 443, protocol: "https", httpStatus: 200, pageTitle: "Nexus Patient Portal", technologies: ["Django", "PostgreSQL", "nginx"], tls: "TLS 1.3 · valid 120d", firstSeen: "2026-08-10T13:00:00Z", lastSeen: "2026-08-28T18:10:00Z", discoverySource: "HTTPx", risk: "high", type: "live_host" },
  { id: "asset_12", targetId: "target_05", targetName: "Nexus Healthcare", hostname: "api.nexushealth.org", domain: "nexushealth.org", ip: "192.0.2.201", port: 443, protocol: "https", httpStatus: 200, pageTitle: "Nexus API", technologies: ["Python", "Django REST"], tls: "TLS 1.3 · valid 120d", firstSeen: "2026-08-10T13:05:00Z", lastSeen: "2026-08-28T18:08:00Z", discoverySource: "Subfinder", risk: "medium", type: "live_host" },
];

export const mockEndpoints: Endpoint[] = [
  { id: "endpoint_01", targetId: "target_01", targetName: "Northstar Customer Portal", assetId: "asset_01", url: "https://portal.northstar-demo.com/search?q=", path: "/search", method: "GET", contentType: "text/html", parameters: [{ name: "q", location: "query", type: "string", required: false }], authenticationRequired: false, observedRole: "public", discoverySource: "Katana", statusCode: 200, fingerprint: "sha256:8eac…79b1", testsCompleted: 8, relatedFindings: 1, firstSeen: "2026-08-12T10:44:00Z", lastSeen: "2026-08-27T09:03:00Z", kind: "web" },
  { id: "endpoint_02", targetId: "target_01", targetName: "Northstar Customer Portal", assetId: "asset_02", url: "https://api.northstar-demo.com/v1/accounts/{accountId}", path: "/v1/accounts/{accountId}", method: "GET", contentType: "application/json", parameters: [{ name: "accountId", location: "path", type: "uuid", required: true }], authenticationRequired: true, observedRole: "customer", discoverySource: "OpenAPI import", statusCode: 200, fingerprint: "sha256:89da…301e", testsCompleted: 12, relatedFindings: 1, firstSeen: "2026-08-12T10:50:00Z", lastSeen: "2026-08-27T09:01:00Z", kind: "api" },
  { id: "endpoint_03", targetId: "target_01", targetName: "Northstar Customer Portal", assetId: "asset_02", url: "https://api.northstar-demo.com/v1/profile", path: "/v1/profile", method: "PATCH", contentType: "application/json", parameters: [{ name: "displayName", location: "body", type: "string", required: false }, { name: "timezone", location: "body", type: "string", required: false }], authenticationRequired: true, observedRole: "customer", discoverySource: "JavaScript extraction", statusCode: 200, fingerprint: "sha256:a122…b9d0", testsCompleted: 9, relatedFindings: 0, firstSeen: "2026-08-12T11:02:00Z", lastSeen: "2026-08-27T08:58:00Z", kind: "javascript" },
  { id: "endpoint_04", targetId: "target_01", targetName: "Northstar Customer Portal", assetId: "asset_01", url: "https://portal.northstar-demo.com/admin/export", path: "/admin/export", method: "POST", contentType: "application/json", parameters: [{ name: "format", location: "body", type: "enum", required: true }], authenticationRequired: true, observedRole: "admin", discoverySource: "Web archive", statusCode: 403, fingerprint: "sha256:0ffd…42cc", testsCompleted: 4, relatedFindings: 1, firstSeen: "2026-08-21T09:30:00Z", lastSeen: "2026-08-27T08:56:00Z", kind: "historical" },
  { id: "endpoint_05", targetId: "target_02", targetName: "Atlas Partner API", assetId: "asset_05", url: "https://sandbox-api.atlas-demo.dev/v2/orders", path: "/v2/orders", method: "POST", contentType: "application/json", parameters: [{ name: "customerId", location: "body", type: "uuid", required: true }, { name: "items", location: "body", type: "array", required: true }], authenticationRequired: true, observedRole: "partner", discoverySource: "OpenAPI import", statusCode: 201, fingerprint: "sha256:215a…f002", testsCompleted: 14, relatedFindings: 1, firstSeen: "2026-08-18T14:30:00Z", lastSeen: "2026-08-26T16:31:00Z", kind: "api" },
  { id: "endpoint_06", targetId: "target_02", targetName: "Atlas Partner API", assetId: "asset_05", url: "https://sandbox-api.atlas-demo.dev/v1/health", path: "/v1/health", method: "GET", contentType: "application/json", parameters: [], authenticationRequired: false, observedRole: "public", discoverySource: "HTTPx", statusCode: 200, fingerprint: "sha256:9a32…cb11", testsCompleted: 5, relatedFindings: 0, firstSeen: "2026-08-18T14:22:00Z", lastSeen: "2026-08-26T16:28:00Z", kind: "api" },
  { id: "endpoint_07", targetId: "target_03", targetName: "Aurora Fintech Web", assetId: "asset_08", url: "https://api.aurora-finance.com/v2/accounts/{accountId}", path: "/v2/accounts/{accountId}", method: "GET", contentType: "application/json", parameters: [{ name: "accountId", location: "path", type: "uuid", required: true }], authenticationRequired: true, observedRole: "customer", discoverySource: "OpenAPI import", statusCode: 200, fingerprint: "sha256:11ab…903f", testsCompleted: 12, relatedFindings: 2, firstSeen: "2026-08-05T09:20:00Z", lastSeen: "2026-08-29T11:24:00Z", kind: "api" },
  { id: "endpoint_08", targetId: "target_03", targetName: "Aurora Fintech Web", assetId: "asset_08", url: "https://api.aurora-finance.com/v2/transfer", path: "/v2/transfer", method: "POST", contentType: "application/json", parameters: [{ name: "from", location: "body", type: "uuid", required: true }, { name: "to", location: "body", type: "uuid", required: true }, { name: "amount", location: "body", type: "number", required: true }], authenticationRequired: true, observedRole: "customer", discoverySource: "JavaScript extraction", statusCode: 201, fingerprint: "sha256:88bc…4421", testsCompleted: 14, relatedFindings: 1, firstSeen: "2026-08-05T09:30:00Z", lastSeen: "2026-08-29T11:22:00Z", kind: "api" },
  { id: "endpoint_09", targetId: "target_03", targetName: "Aurora Fintech Web", assetId: "asset_07", url: "https://app.aurora-finance.com/dashboard", path: "/dashboard", method: "GET", contentType: "text/html", parameters: [], authenticationRequired: true, observedRole: "customer", discoverySource: "Katana", statusCode: 200, fingerprint: "sha256:ab12…77ff", testsCompleted: 6, relatedFindings: 1, firstSeen: "2026-08-05T09:12:00Z", lastSeen: "2026-08-29T11:25:00Z", kind: "web" },
  { id: "endpoint_10", targetId: "target_05", targetName: "Nexus Healthcare", assetId: "asset_12", url: "https://api.nexushealth.org/v1/patients/{patientId}/records", path: "/v1/patients/{patientId}/records", method: "GET", contentType: "application/json", parameters: [{ name: "patientId", location: "path", type: "uuid", required: true }], authenticationRequired: true, observedRole: "clinician", discoverySource: "OpenAPI import", statusCode: 200, fingerprint: "sha256:ca3d…10ab", testsCompleted: 10, relatedFindings: 1, firstSeen: "2026-08-10T13:30:00Z", lastSeen: "2026-08-28T18:12:00Z", kind: "api" },
  { id: "endpoint_11", targetId: "target_05", targetName: "Nexus Healthcare", assetId: "asset_11", url: "https://portal.nexushealth.org/phr/download", path: "/phr/download", method: "POST", contentType: "application/json", parameters: [{ name: "format", location: "body", type: "enum", required: true }], authenticationRequired: true, observedRole: "patient", discoverySource: "Web archive", statusCode: 200, fingerprint: "sha256:55de…9081", testsCompleted: 4, relatedFindings: 0, firstSeen: "2026-08-11T14:00:00Z", lastSeen: "2026-08-28T18:09:00Z", kind: "historical" },
  { id: "endpoint_12", targetId: "target_03", targetName: "Aurora Fintech Web", assetId: "asset_08", url: "https://api.aurora-finance.com/graphql", path: "/graphql", method: "POST", contentType: "application/json", parameters: [{ name: "query", location: "body", type: "string", required: true }], authenticationRequired: true, observedRole: "customer", discoverySource: "GraphQL introspection", statusCode: 200, fingerprint: "sha256:0f01…c2d3", testsCompleted: 9, relatedFindings: 2, firstSeen: "2026-08-06T10:40:00Z", lastSeen: "2026-08-29T11:21:00Z", kind: "api" },
];

export const mockScans: Scan[] = [
  { id: "scan_01", name: "Northstar balanced scan", targetName: "Northstar Customer Portal", status: "running", progress: 68, phase: "Active testing", profile: "Balanced", findings: 7, startedAt: "2026-08-27T08:42:00Z", completedAt: null },
  { id: "scan_02", name: "Atlas API passive review", targetName: "Atlas Partner API", status: "completed", progress: 100, phase: "Complete", profile: "API focused", findings: 4, startedAt: "2026-08-26T15:22:00Z", completedAt: "2026-08-26T16:10:00Z" },
  { id: "scan_03", name: "Northstar weekly recon", targetName: "Northstar Customer Portal", status: "completed", progress: 100, phase: "Complete", profile: "Recon only", findings: 2, startedAt: "2026-08-24T06:00:00Z", completedAt: "2026-08-24T06:39:00Z" },
  { id: "scan_04", name: "Aurora full assessment", targetName: "Aurora Fintech Web", status: "running", progress: 44, phase: "Passive Analysis", profile: "Full scan", findings: 6, startedAt: "2026-08-29T10:00:00Z", completedAt: null },
  { id: "scan_05", name: "Aurora API security sweep", targetName: "Aurora Fintech Web", status: "queued", progress: 0, phase: "Queued", profile: "API focused", findings: 0, startedAt: "2026-08-29T11:00:00Z", completedAt: null },
  { id: "scan_06", name: "Nexus PHI compliance scan", targetName: "Nexus Healthcare", status: "completed", progress: 100, phase: "Complete", profile: "Balanced", findings: 9, startedAt: "2026-08-28T17:00:00Z", completedAt: "2026-08-28T18:05:00Z" },
];

export const mockFindings: Finding[] = [
  { id: "finding_01", title: "Reflected cross-site scripting", severity: "high", confidence: 96, verificationState: "confirmed", targetName: "Northstar Customer Portal", endpoint: "GET /search?q=", source: "PAN XSS", createdAt: "2026-08-27T09:08:00Z" },
  { id: "finding_02", title: "Broken object-level authorization", severity: "critical", confidence: 91, verificationState: "high_confidence", targetName: "Northstar Customer Portal", endpoint: "GET /v1/accounts/{accountId}", source: "API scanner", createdAt: "2026-08-27T09:02:00Z" },
  { id: "finding_03", title: "Missing Content-Security-Policy", severity: "medium", confidence: 100, verificationState: "confirmed", targetName: "Northstar Customer Portal", endpoint: "GET /", source: "Passive rules", createdAt: "2026-08-27T08:57:00Z" },
  { id: "finding_04", title: "Excessive data exposure", severity: "medium", confidence: 82, verificationState: "candidate", targetName: "Atlas Partner API", endpoint: "POST /v2/orders", source: "API scanner", createdAt: "2026-08-26T16:02:00Z" },
  { id: "finding_05", title: "Verbose server header", severity: "low", confidence: 100, verificationState: "confirmed", targetName: "Atlas Partner API", endpoint: "GET /v1/health", source: "Passive rules", createdAt: "2026-08-26T15:48:00Z" },
  { id: "finding_06", title: "IDOR on account enumeration", severity: "critical", confidence: 89, verificationState: "candidate", targetName: "Aurora Fintech Web", endpoint: "GET /v2/accounts/{accountId}", source: "API scanner", createdAt: "2026-08-29T11:20:00Z" },
  { id: "finding_07", title: "GraphQL introspection enabled", severity: "high", confidence: 95, verificationState: "confirmed", targetName: "Aurora Fintech Web", endpoint: "POST /graphql", source: "API scanner", createdAt: "2026-08-29T11:12:00Z" },
  { id: "finding_08", title: "Hardcoded API token in bundle", severity: "high", confidence: 87, verificationState: "candidate", targetName: "Aurora Fintech Web", endpoint: "GET /app.js", source: "Secrets scanner", createdAt: "2026-08-29T11:05:00Z" },
  { id: "finding_09", title: "Patient record exposure", severity: "critical", confidence: 93, verificationState: "high_confidence", targetName: "Nexus Healthcare", endpoint: "GET /v1/patients/{patientId}/records", source: "API scanner", createdAt: "2026-08-28T18:00:00Z" },
  { id: "finding_10", title: "Missing rate limiting on login", severity: "medium", confidence: 78, verificationState: "candidate", targetName: "Nexus Healthcare", endpoint: "POST /auth/login", source: "Passive rules", createdAt: "2026-08-28T17:52:00Z" },
  { id: "finding_11", title: "Weak TLS cipher suites", severity: "low", confidence: 90, verificationState: "confirmed", targetName: "Nexus Healthcare", endpoint: "GET /", source: "Passive rules", createdAt: "2026-08-28T17:40:00Z" },
  { id: "finding_12", title: "Stored XSS in profile bio", severity: "high", confidence: 84, verificationState: "candidate", targetName: "Northstar Customer Portal", endpoint: "PATCH /v1/profile", source: "PAN XSS", createdAt: "2026-08-28T09:30:00Z" },
];

export const mockNotifications: Notification[] = [
  { id: "notification_01", category: "finding", title: "Critical candidate needs review", message: "A possible BOLA issue was correlated across two authenticated roles.", createdAt: "2026-08-27T09:04:00Z", read: false, severity: "danger", href: "/findings/finding_02/overview" },
  { id: "notification_02", category: "scan", title: "Balanced scan is 68% complete", message: "Active testing is running within the approved Northstar scope.", createdAt: "2026-08-27T08:58:00Z", read: false, severity: "info", href: "/scans/scan_01/live" },
  { id: "notification_03", category: "asset", title: "New subdomain discovered", message: "status.northstar-demo.com was added to the asset inventory.", createdAt: "2026-08-27T08:47:00Z", read: false, severity: "warning", href: "/assets/asset_04" },
  { id: "notification_04", category: "scan", title: "Atlas API scan completed", message: "128 endpoints were covered and four findings were normalized.", createdAt: "2026-08-26T16:10:00Z", read: true, severity: "success", href: "/scans/scan_02/overview" },
  { id: "notification_05", category: "finding", title: "IDOR candidate on Aurora", message: "Account enumeration via /v2/accounts flagged with 89% confidence.", createdAt: "2026-08-29T11:21:00Z", read: false, severity: "danger", href: "/findings/finding_06/overview" },
  { id: "notification_06", category: "scan", title: "Nexus PHI scan completed", message: "9 findings normalized, including a critical record-exposure candidate.", createdAt: "2026-08-28T18:06:00Z", read: false, severity: "warning", href: "/scans/scan_06/overview" },
  { id: "notification_07", category: "asset", title: "3 assets added to Aurora", message: "payments, mobile, and cdn subdomains were fingerprinted.", createdAt: "2026-08-29T11:18:00Z", read: false, severity: "info", href: "/assets/all" },
];

export const mockDashboard: DashboardSummary = {
  metrics: { targets: 5, verifiedAssets: 89, endpoints: 1523, runningScans: 2, confirmedFindings: 12, candidateFindings: 19 },
  severity: { critical: 3, high: 7, medium: 11, low: 9, informational: 4 },
  trend: [
    { label: "Aug 21", critical: 0, high: 3, medium: 5, resolved: 1 },
    { label: "Aug 22", critical: 0, high: 4, medium: 6, resolved: 1 },
    { label: "Aug 23", critical: 1, high: 4, medium: 8, resolved: 2 },
    { label: "Aug 24", critical: 2, high: 6, medium: 10, resolved: 4 },
    { label: "Aug 25", critical: 2, high: 5, medium: 9, resolved: 6 },
    { label: "Aug 26", critical: 2, high: 6, medium: 11, resolved: 8 },
    { label: "Today", critical: 3, high: 7, medium: 11, resolved: 10 },
  ],
  recentAssets: mockAssets.slice(0, 6),
  recentScans: mockScans,
  recentFindings: mockFindings.slice(0, 5),
  securityScore: 72,
  coverage: 88,
};
